{ config, pkgs, ... }:

{
  # User Packages: Helper tools for Hyprland integration.
  home.packages = [
    pkgs.jq    # Command-line JSON processor.
    pkgs.socat # Multipurpose relay (used to listen to Hyprland sockets).
    
    # launch-tui: A script to launch terminal applications in a floating window.
    (pkgs.writeShellScriptBin "launch-tui" ''
      ${pkgs.ghostty}/bin/ghostty --title="launch-tui" -e "$@"
    '')
    
    # hypr-tabswitch-daemon: A complex script that manages window switching via Noctalia Tabber.
    # It ensures that if you switch windows while in fullscreen, the new window also becomes fullscreen.
    (pkgs.writeShellScriptBin "hypr-tabswitch-daemon" ''
  SOCKET="$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"
  
  SAVED_FS=0
  TABBER_OPEN=0

  # Listen to Hyprland events via socat.
  ${pkgs.socat}/bin/socat - UNIX-CONNECT:"$SOCKET" 2>/dev/null | \
    while IFS= read -r line; do
      case "$line" in
        openlayer\>\>tabber-*)
          # When Noctalia Tabber opens, save the current window's address and fullscreen state.
          SAVED_FS=$(hyprctl activewindow -j | ${pkgs.jq}/bin/jq '.fullscreen')
          SAVED_ADDR=$(hyprctl activewindow -j | ${pkgs.jq}/bin/jq -r '.address')
          TABBER_OPEN=1
          ;;
        closelayer\>\>tabber-*)
          TABBER_OPEN=0
          ;;
        activewindow\>*)
          # When a new window becomes active after Tabber closes, restore the fullscreen state if needed.
          if [ "$TABBER_OPEN" = "0" ] && [ "$SAVED_FS" != "0" ]; then
            sleep 0.05
            CURRENT_ADDR=$(hyprctl activewindow -j | ${pkgs.jq}/bin/jq -r '.address')
            CURRENT_FS=$(hyprctl activewindow -j | ${pkgs.jq}/bin/jq '.fullscreen')
            
            # If the focused window changed and is NOT already fullscreen, apply the saved state.
            if [ "$CURRENT_ADDR" != "$SAVED_ADDR" ] && [ "$CURRENT_FS" != "$SAVED_FS" ]; then
              if [ "$SAVED_FS" = "2" ]; then
                hyprctl dispatch fullscreen 0 # Real fullscreen.
              elif [ "$SAVED_FS" = "1" ]; then
                hyprctl dispatch fullscreen 1 # Maximized (client-side).
              fi
            fi
            SAVED_FS=0
            SAVED_ADDR=""
          fi
          ;;
      esac
    done
'')

# hypr-tabswitch: Trigger the Noctalia Tabber window switcher.
(pkgs.writeShellScriptBin "hypr-tabswitch" ''
  DIRECTION=''${1:-next}
  hyprctl dispatch global tabber:select-''${DIRECTION}
'')
  ];

  # Hyprland User Settings
  wayland.windowManager.hyprland = {
    enable = true;
    systemd.enable = true; # Let Home Manager manage the Hyprland systemd target.
    systemd.variables = [ "--all" ];
    configType = "hyprlang";
    extraConfig = ''
      debug:disable_logs = false
    '';
    settings = {
      # Monitor Configuration: 1080p @ 144Hz with 1.25 scaling.
      monitor = [
        "eDP-1, 1920x1080@144, 0x0, 1.25"
      ];
      autogenerated = 0;
      "$mod" = "SUPER";

      # Layer Rules: Specific tweaks for UI layers (like the bar or launcher).
      layerrule = [
        "blur on, match:namespace ^noctalia.*$"
        "ignore_alpha 0.6, match:namespace ^noctalia.*$" # Required for rounded corners/shadows on transparent bars.
      ];

      # Window Rules: Control how specific windows behave.
      windowrule = [
        "float true, match:title ^(launch-tui)$"
        "center true, match:title ^(launch-tui)$"
        "size 70% 70%, match:title ^(launch-tui)$"
      ];

      # Autostart: Programs to launch when Hyprland starts.
      exec-once = [
        "noctalia-shell"           # The main shell/bar.
        "hypr-tabswitch-daemon"   # The fullscreen-aware window switcher helper.
      ];

      # General: Basic look and feel.
      general = {
        gaps_in = 5;
        gaps_out = 8;
        border_size = 2;
        "col.active_border" = "rgba(b4befeee) rgba(cba6f7ee) 45deg"; # Lavender to Mauve gradient.
        "col.inactive_border" = "rgba(313244ee)";
        layout = "dwindle";
      };

      # Decoration: Transparency, shadows, and blur.
      decoration = {
        rounding = 4;
        active_opacity = 0.85;
        inactive_opacity = 0.75;

        shadow = {
          enabled = false;
          range = 30;
          render_power = 3;
        };

        blur = {
          enabled = true;
          size = 10;
          passes = 3;
          ignore_opacity = true;
          xray = true;           # Better performance and look for blur.
          contrast = 0.8916;
          brightness = 0.8172;
          vibrancy = 0.1696;
          noise = 0.0117;
        };
      };

      # Animations: Bezier curves and speed settings.
      animations = {
        enabled = true;
        bezier = [
          "easeOutQuint,0.23,1,0.32,1"
          "easeInOutCubic,0.65,0.05,0.36,1"
          "linear,0,0,1,1"
          "almostLinear,0.5,0.5,0.75,1.0"
          "quick,0.15,0,0.1,1"
        ];
        animation = [
          "border, 1, 5.39, easeOutQuint"
          "windows, 1, 4.79, easeOutQuint"
          "windowsIn, 1, 4.1, easeOutQuint, popin 87%"
          "windowsOut, 1, 1.49, linear, popin 87%"
          "fadeIn, 1, 1.73, almostLinear"
          "fadeOut, 1, 1.46, almostLinear"
          "fade, 1, 3.03, quick"
          "layers, 1, 3.81, easeOutQuint"
          "layersIn, 1, 4, easeOutQuint, fade"
          "layersOut, 1, 1.5, linear, fade"
          "fadeLayersIn, 1, 1.79, almostLinear"
          "fadeLayersOut, 1, 1.39, almostLinear"
          "workspaces, 1, 3, easeOutQuint"
        ];
      };

      # Dwindle: The default tiling layout behavior.
      dwindle = {
        preserve_split = true;
        force_split = 2;       # New windows split the area into two.
      };

      debug = {
        disable_logs = false;
        enable_stdout_logs = true;
      };

      misc = {
        exit_window_retains_fullscreen = true; # Required for our custom tabswitch daemon.
      };

      # Keybindings: $mod = SUPER (Windows key).
      bind = [
        "$mod, ESCAPE, exec, noctalia-shell ipc call sessionMenu toggle"
        "$mod, RETURN, exec, ghostty"
        "$mod, SPACE, exec, noctalia-shell ipc call launcher toggle"
        "$mod SHIFT, W, exec, noctalia-shell ipc call plugin:wallcards toggle"
        "$mod SHIFT, Q, exit"
        "$mod, W, killactive"
        "$mod, F, fullscreen, 0"
        "$mod, M, fullscreen, 1"
        "$mod, T, togglefloating"
        "$mod, P, pseudo"
        "$mod, I, layoutmsg, togglesplit"
        "$mod CTRL, L, exec, loginctl lock-session"

        # Alt+Tab (Noctalia Tabber plugin) - fullscreen-aware
        "ALT, TAB, exec, hypr-tabswitch next"
        "ALT SHIFT, TAB, exec, hypr-tabswitch prev"
        "ALT, Q, exec, noctalia-shell ipc call plugin:tabber action close"

        # Focus (Vim-style)
        "$mod, H, movefocus, l"
        "$mod, L, movefocus, r"
        "$mod, K, movefocus, u"
        "$mod, J, movefocus, d"

        # Swap windows
        "$mod SHIFT, H, swapwindow, l"
        "$mod SHIFT, L, swapwindow, r"
        "$mod SHIFT, K, swapwindow, u"
        "$mod SHIFT, J, swapwindow, d"

        # Resize
        "$mod, minus, resizeactive, -100 0"
        "$mod, equal, resizeactive, 100 0"
        "$mod SHIFT, minus, resizeactive, 0 -100"
        "$mod SHIFT, equal, resizeactive, 0 100"

        # Special workspace
        "$mod, S, togglespecialworkspace, magic"
        "$mod SHIFT, S, movetoworkspace, special:magic"

        # Switch workspaces
        "$mod, 1, workspace, 1"
        "$mod, 2, workspace, 2"
        "$mod, 3, workspace, 3"
        "$mod, 4, workspace, 4"
        "$mod, 5, workspace, 5"
        "$mod, 6, workspace, 6"
        "$mod, 7, workspace, 7"
        "$mod, 8, workspace, 8"
        "$mod, 9, workspace, 9"
        "$mod, 0, workspace, 10"

        # Move to workspace
        "$mod SHIFT, 1, movetoworkspace, 1"
        "$mod SHIFT, 2, movetoworkspace, 2"
        "$mod SHIFT, 3, movetoworkspace, 3"
        "$mod SHIFT, 4, movetoworkspace, 4"
        "$mod SHIFT, 5, movetoworkspace, 5"
        "$mod SHIFT, 6, movetoworkspace, 6"
        "$mod SHIFT, 7, movetoworkspace, 7"
        "$mod SHIFT, 8, movetoworkspace, 8"
        "$mod SHIFT, 9, movetoworkspace, 9"
        "$mod SHIFT, 0, movetoworkspace, 10"
      ];

      # Mouse Bindings: Move and Resize with SUPER + Left/Right click.
      bindm = [
        "$mod, mouse:272, movewindow"
        "$mod, mouse:273, resizewindow"
      ];
    };
  };
}