{ config, pkgs, ... }:

{
  home.packages = [
    pkgs.jq
    pkgs.socat
    (pkgs.writeShellScriptBin "launch-tui" ''
      ${pkgs.ghostty}/bin/ghostty --title="launch-tui" -e "$@"
    '')
    (pkgs.writeShellScriptBin "hypr-tabswitch-daemon" ''
  SOCKET="$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock"
  
  SAVED_FS=0
  TABBER_OPEN=0

  ${pkgs.socat}/bin/socat - UNIX-CONNECT:"$SOCKET" 2>/dev/null | \
    while IFS= read -r line; do
      case "$line" in
        openlayer\>\>tabber-*)
          # Tabber just opened — save current fullscreen state
          SAVED_FS=$(hyprctl activewindow -j | ${pkgs.jq}/bin/jq '.fullscreen')
          SAVED_ADDR=$(hyprctl activewindow -j | ${pkgs.jq}/bin/jq -r '.address')
          TABBER_OPEN=1
          echo "[daemon] tabber opened, saved fs=$SAVED_FS addr=$SAVED_ADDR" >> /tmp/hypr-tabswitch.log
          ;;
        closelayer\>\>tabber-*)
          TABBER_OPEN=0
          echo "[daemon] tabber closed" >> /tmp/hypr-tabswitch.log
          ;;
        activewindow\>*)
          if [ "$TABBER_OPEN" = "0" ] && [ "$SAVED_FS" != "0" ]; then
            # Tabber is closed and we have a saved fullscreen state
            sleep 0.05
            CURRENT_ADDR=$(hyprctl activewindow -j | ${pkgs.jq}/bin/jq -r '.address')
            CURRENT_FS=$(hyprctl activewindow -j | ${pkgs.jq}/bin/jq '.fullscreen')
            echo "[daemon] activewindow after close: addr=$CURRENT_ADDR fs=$CURRENT_FS saved_fs=$SAVED_FS" >> /tmp/hypr-tabswitch.log
            if [ "$CURRENT_ADDR" != "$SAVED_ADDR" ] && [ "$CURRENT_FS" != "$SAVED_FS" ]; then
              echo "[daemon] restoring fullscreen $SAVED_FS" >> /tmp/hypr-tabswitch.log
              if [ "$SAVED_FS" = "2" ]; then
                hyprctl dispatch fullscreen 0
              elif [ "$SAVED_FS" = "1" ]; then
                hyprctl dispatch fullscreen 1
              fi
            fi
            SAVED_FS=0
            SAVED_ADDR=""
          fi
          ;;
      esac
    done
'')

(pkgs.writeShellScriptBin "hypr-tabswitch" ''
  DIRECTION=''${1:-next}
  hyprctl dispatch global tabber:select-''${DIRECTION}
'')
  ];

  wayland.windowManager.hyprland = {
    enable = true;
    configType = "hyprlang";
    extraConfig = ''
      debug:disable_logs = false
    '';
    settings = {
      monitor = [
        "eDP-1, 1920x1080@144, 0x0, 1.25"
      ];
      autogenerated = 0;
      "$mod" = "SUPER";

      layerrule = [
        "blur on, match:namespace ^noctalia.*$"
        "ignore_alpha 0.6, match:namespace ^noctalia.*$"
      ];

      windowrule = [
        "float true, match:title ^(launch-tui)$"
        "center true, match:title ^(launch-tui)$"
        "size 70% 70%, match:title ^(launch-tui)$"
      ];

      exec-once = [
        "noctalia-shell"
        "hypr-tabswitch-daemon"
      ];

      general = {
        gaps_in = 5;
        gaps_out = 8;
        border_size = 2;
        "col.active_border" = "rgba(b4befeee) rgba(cba6f7ee) 45deg";
        "col.inactive_border" = "rgba(313244ee)";
        layout = "dwindle";
      };

      decoration = {
        rounding = 4;
        active_opacity = 0.85;
        inactive_opacity = 0.75;

        shadow = {
          enabled = false;
          range = 30;
          render_power = 3;
        };

        blur = {
          enabled = true;
          size = 10;
          passes = 3;
          ignore_opacity = true;
          xray = true;
          contrast = 0.8916;
          brightness = 0.8172;
          vibrancy = 0.1696;
          noise = 0.0117;
        };
      };

      animations = {
        enabled = true;
        bezier = [
          "easeOutQuint,0.23,1,0.32,1"
          "easeInOutCubic,0.65,0.05,0.36,1"
          "linear,0,0,1,1"
          "almostLinear,0.5,0.5,0.75,1.0"
          "quick,0.15,0,0.1,1"
        ];
        animation = [
          "border, 1, 5.39, easeOutQuint"
          "windows, 1, 4.79, easeOutQuint"
          "windowsIn, 1, 4.1, easeOutQuint, popin 87%"
          "windowsOut, 1, 1.49, linear, popin 87%"
          "fadeIn, 1, 1.73, almostLinear"
          "fadeOut, 1, 1.46, almostLinear"
          "fade, 1, 3.03, quick"
          "layers, 1, 3.81, easeOutQuint"
          "layersIn, 1, 4, easeOutQuint, fade"
          "layersOut, 1, 1.5, linear, fade"
          "fadeLayersIn, 1, 1.79, almostLinear"
          "fadeLayersOut, 1, 1.39, almostLinear"
          "workspaces, 1, 3, easeOutQuint"
        ];
      };

      dwindle = {
        preserve_split = true;
        force_split = 2;
      };

      debug = {
        disable_logs = false;
        enable_stdout_logs = true;
      };

      misc = {
        exit_window_retains_fullscreen = true;
      };

      bind = [
        "$mod, ESCAPE, exec, noctalia-shell ipc call sessionMenu toggle"
        "$mod, RETURN, exec, ghostty"
        "$mod, SPACE, exec, noctalia-shell ipc call launcher toggle"
        "$mod SHIFT, W, exec, noctalia-shell ipc call plugin:wallcards toggle"
        "$mod SHIFT, Q, exit"
        "$mod, W, killactive"
        "$mod, F, fullscreen, 0"
        "$mod, M, fullscreen, 1"
        "$mod, T, togglefloating"
        "$mod, P, pseudo"
        "$mod, I, layoutmsg, togglesplit"

        # Alt+Tab (Noctalia Tabber plugin) - fullscreen-aware
        "ALT, TAB, exec, hypr-tabswitch next"
        "ALT SHIFT, TAB, exec, hypr-tabswitch prev"
        "ALT, Q, exec, noctalia-shell ipc call plugin:tabber action close"

        # Focus (Vim-style)
        "$mod, H, movefocus, l"
        "$mod, L, movefocus, r"
        "$mod, K, movefocus, u"
        "$mod, J, movefocus, d"

        # Swap windows
        "$mod SHIFT, H, swapwindow, l"
        "$mod SHIFT, L, swapwindow, r"
        "$mod SHIFT, K, swapwindow, u"
        "$mod SHIFT, J, swapwindow, d"

        # Resize
        "$mod, minus, resizeactive, -100 0"
        "$mod, equal, resizeactive, 100 0"
        "$mod SHIFT, minus, resizeactive, 0 -100"
        "$mod SHIFT, equal, resizeactive, 0 100"

        # Special workspace
        "$mod, S, togglespecialworkspace, magic"
        "$mod SHIFT, S, movetoworkspace, special:magic"

        # Switch workspaces
        "$mod, 1, workspace, 1"
        "$mod, 2, workspace, 2"
        "$mod, 3, workspace, 3"
        "$mod, 4, workspace, 4"
        "$mod, 5, workspace, 5"
        "$mod, 6, workspace, 6"
        "$mod, 7, workspace, 7"
        "$mod, 8, workspace, 8"
        "$mod, 9, workspace, 9"
        "$mod, 0, workspace, 10"

        # Move to workspace
        "$mod SHIFT, 1, movetoworkspace, 1"
        "$mod SHIFT, 2, movetoworkspace, 2"
        "$mod SHIFT, 3, movetoworkspace, 3"
        "$mod SHIFT, 4, movetoworkspace, 4"
        "$mod SHIFT, 5, movetoworkspace, 5"
        "$mod SHIFT, 6, movetoworkspace, 6"
        "$mod SHIFT, 7, movetoworkspace, 7"
        "$mod SHIFT, 8, movetoworkspace, 8"
        "$mod SHIFT, 9, movetoworkspace, 9"
        "$mod SHIFT, 0, movetoworkspace, 10"
      ];

      bindm = [
        "$mod, mouse:272, movewindow"
        "$mod, mouse:273, resizewindow"
      ];
    };
  };
}